# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  - jekyll-sitemap

defaults:
  -
    values:
      layout: marquee
      main_nav: no

exclude:
  - "/vendor/"

# Site settings
title: PhysioAge Help
subtitle: "Documentation for the PhysioAge community."
email: team@physioage.com
name: PhysioAge Systems
description: >
  "Documentation for the PhysioAge community."
# Google analytics
ga_tracking_id: "UA-104207032-5"

url: "https://support.physioage.com" # the base hostname & protocol for your site
cover: "/assets/marquee_banner.svg"
logo: "/assets/logo_physioage.png"

# # Archive settings (see https://github.com/jekyll/jekyll-archives/)
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layout: 'archive'
#   permalinks:
#     category: '/category/:name/'
#     tag: '/tag/:name/'
#
# # Disqus comments
# # disqus_shortname: bencentra

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
#
# Example:
#
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: PhysioAge
    url: https://twitter.com/PhysioAge
    desc: Follow us on Twitter
    share: true

  - name: YouTube
    icon: youtube
    username:
    url:
    desc: Subscribe on YouTube
    share: false
